"""Backend-neutral timing plans and local processing for generated speech."""

from .alignment import DefaultTimingAlignmentEngine, TimingAlignmentEngine
from .mixing import AudioTimelineMixer, FFmpegAudioTimelineMixer
from .models import (
    AlignmentAction,
    AudioMixingConfig,
    AudioMixingError,
    AudioMixingFailedError,
    AudioMixingPlan,
    AudioProcessingError,
    AudioProcessingFailedError,
    AudioProcessingResult,
    AudioStreamInfo,
    InvalidAlignmentConfigurationError,
    InvalidAlignmentSegmentError,
    InvalidAudioMixingConfigurationError,
    InvalidAudioMixingInputError,
    InvalidAudioProcessingInputError,
    MissingAudioMixingDependencyError,
    MissingAudioProcessingDependencyError,
    MixedAudioResult,
    ProcessedAudioSegment,
    TimelinePlacement,
    TimingAlignmentConfig,
    TimingAlignmentError,
    TimingAlignmentInstruction,
    TimingAlignmentResult,
)
from .processing import AudioTimingProcessor, FFmpegAudioTimingProcessor

__all__ = [
    "AlignmentAction",
    "AudioMixingConfig",
    "AudioMixingError",
    "AudioMixingFailedError",
    "AudioMixingPlan",
    "AudioProcessingError",
    "AudioProcessingFailedError",
    "AudioProcessingResult",
    "AudioStreamInfo",
    "AudioTimelineMixer",
    "AudioTimingProcessor",
    "DefaultTimingAlignmentEngine",
    "FFmpegAudioTimelineMixer",
    "FFmpegAudioTimingProcessor",
    "InvalidAlignmentConfigurationError",
    "InvalidAlignmentSegmentError",
    "InvalidAudioMixingConfigurationError",
    "InvalidAudioMixingInputError",
    "InvalidAudioProcessingInputError",
    "MissingAudioMixingDependencyError",
    "MissingAudioProcessingDependencyError",
    "MixedAudioResult",
    "ProcessedAudioSegment",
    "TimelinePlacement",
    "TimingAlignmentConfig",
    "TimingAlignmentEngine",
    "TimingAlignmentError",
    "TimingAlignmentInstruction",
    "TimingAlignmentResult",
]
